### ISSUE TITLE
Copy lib/mercadopago.rb

### ISSUE THREAD

**Issue by juancroca** [mercadopago/sdk-ruby#11]
I was checking out how this gem works to integrate with an app I'm currently developing, but was surprised to see that for it to function correctly you have to copy and require an .rb file. This in my opinion defeats the purpose of it being a gem since when updating the gem will require to replace that .rb file every time you update. I would rather use this gem since its supported by the same team from the platform but think this issue should be corrected, maybe checkout this other gem that does something similar to what you want to accomplish https://github.com/kauplus/mercadopago

**Comment by hcasatti** [comment]
It was just a Readme update mistake. Now is fixed. You can install the gem as usual.
