### ISSUE TITLE
ERROR: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by arielscherman** [mercadopago/sdk-ruby#13]
I am using this gem and sometimes it works, and sometimes it returns the next error:
"A JSON text must at least contain two octets!"

Sometimes it explode when i call the method "get_access_token()" and sometimes when i call the method "create_preference()"

**Comment by cavi21** [comment]
hi! the service is very very unstable right now, after the rollout of the **not use SSLv3** seems that there are some servers that are still try to deal with that protocol, @sebagun do you have any insight for how long this is going to be? is there any update?

**Comment by arielscherman** [comment]
Thanks @cavi21, and what should i do? I mean... is there an alternative way to do that or should i just sit and hope my future website will be able to work with mercadopago? haha thanks

**Comment by cavi21** [comment]
@arielscherman haha! yep that's the only option right now, or do something that it's not recommended that is to setup ```verify_ssl = false``` that is NOT a good practice at all :warning:!!

Also in order for @hcasatti and @sebagun to know, it seems that the server in **63.128.82.9** is at least one of the *trouble makers* as you can see in this image:
![screen shot 2015-03-26 at 5 29 17 pm](https://cloud.githubusercontent.com/assets/146249/6856315/010a438c-d3de-11e4-97ad-b99eb0ef0b56.png)
As you can see in there that when the `Socket.getaddrinfo` replied **216.33.196.254** I could get the *access_token* but if replied **63.128.82.9** I got the error:
```ruby
JSON::ParserError: A JSON text must at least contain two octets!
from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/2.2.0/json/common.rb:155:in `initialise'
```
Any update is appreciate it!
Thanks guys
