### ISSUE TITLE
bad_request error - Params Error

### ISSUE THREAD

**Issue by cavi21** [mercadopago/sdk-ruby#14]
Hi there! The API seems to be with some trouble right? because it's answering when I try to load the token

```ruby
"message" => "Params Error",
    "error" => "bad_request",
   "status" => 400,
    "cause" => {
           "code" => 1,
    "description" => "Params Error",
           "data" => nil
  }
```
is there insight on this?

**Comment by hcasatti** [comment]
Could you try again ?
We've just deployed some changes in order to fix this problem.






*Horacio E. Casatti*
Sr. Software Engineer - La Punta - San Luis
horacio.casatti@mercadolibre.com
Int. 1648

**Comment by cavi21** [comment]
I just try again and everything was looking fine! thanks! I close this

**Comment by francofadini** [comment]
Sandbox is getting this same error since 11am 12/01/2017

**Comment by gcarignano** [comment]
The: "Params Error - 1: Params Error" is back.
