### ISSUE TITLE
The JS library that is in the Docs is broken

### ISSUE THREAD

**Issue by cavi21** [mercadopago/sdk-ruby#15]
Hey guys, trying to implement the custom checkout and the library that is the in **[docs](http://labs.mercadopago.com.ar/developers/es/tools/sdk/client/javascript/)** have issues when calling **[#getPaymentMethod](http://labs.mercadopago.com.ar/developers/es/tools/sdk/client/javascript/#get-pm-info)** with a bin, I'm doing the call this way:
```javascript
Mercadopago.getPaymentMethod( { "bin": '4509 9535' }, MP.setPaymentMethodInfo)
```
And I'm getting this error:
```javascript
TypeError: b.bin is undefined
k.validateBinPattern()mercadopago.js (line 1)
l()mercadopago.js (line 1)
l()mercadopago.js (line 1)
k.getPaymentMethod()
```

There are a few other stuff that's weird like the **[docs](http://labs.mercadopago.com.ar/developers/es/tools/sdk/client/javascript/)** mention to load this library:
```html
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
```
And in all of your examples in **[here](https://github.com/mercadopago/code-examples)** you are loading this library:
```html
<script type="text/javascript" src="https://secure.mlstatic.com/org-img/checkout/custom/1.0/checkout.js"></script>
```
Also have a hard time trying to contact with anyone in there through the email developers@mercadopago.com is there a way to contact anyone a little bit more quickly for this kind of things? also in order to move the implementation to production?
Thanks!

**Comment by sebagun** [comment]
@cavi21 you should send the bin as first six digits only, without blank spaces:
```
Mercadopago.getPaymentMethod( { "bin": '450995' }, MP.setPaymentMethodInfo)
```
Please use 
```
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
```
as your SDK source. The other that you may see in that repo, has sense in examples for previous integrations, not yours.

Regards

**Comment by cavi21** [comment]
I just replied it in this other [thread](https://github.com/mercadopago/sdk-nodejs/issues/12)

**Comment by cavi21** [comment]
@sebagun or @hcasatti did you see the other thread I mention??
Thanks
