### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by hugoerg56** [mercadopago/sdk-ruby#21]
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by Kyterneser** [comment]
Following the guide:

http://guides.rubygems.org/ssl-certificate-update/

**Comment by Kyterneser** [comment]
Try this: http://guides.rubygems.org/ssl-certificate-update/

**Comment by joelibaceta** [comment]
You are getting this error because we explicitly don't allow to use SSLv3 https://github.com/mercadopago/sdk-ruby/blob/master/lib/mercadopago.rb#L302
