### ISSUE TITLE
Can't retrive a made payment

### ISSUE THREAD

**Issue by cunib** [mercadopago/sdk-ruby#22]
I trie it with a preference made with sandbox mode (sandobox: true) and with (sandbox: false) and saccesfull payments but i can't get the payment information.

With $mp..search_payment Hash[], 0,50 
I get:
{"status"=>"200", "response"=>{"paging"=>{"total"=>0, "limit"=>50, "offset"=>0}, "results"=>[]}} 
And with $mp.get_payment "/payments/:id 
allways return:
{"status"=>"404", "response"=>{"message"=>"Resource /collections/notifications//payments/:id not found.", "error"=>"not_found", "status"=>404, "cause"=>[]}}

I'd try with diferents payments ids, but the api allways respond with "Not found".

**Comment by joelibaceta** [comment]
Resource /collections/ ... has been deprecated. You should use /v1/payments instead of that.
