### ISSUE TITLE
Integration to rails project

### ISSUE THREAD

**Issue by javla** [mercadopago/sdk-ruby#25]
Hi,
I'm working on a web page where users can buy and sell their products. I want that customers can pay with credit cards through the MercadoPago.

Is it posible to do something like that?

If it is, what I have to do? Because I have read the developers documentation and cannot achieve my goal.

Thanks in advance.

**Comment by joelibaceta** [comment]
Visit the official support channel for this questions.  https://www.mercadopago.com.ar/developers/es/support
