### ISSUE TITLE
TypeError (MercadoPago is not a class)

### ISSUE THREAD

**Issue by LuisDominguez** [mercadopago/sdk-ruby#26]
When i call
require 'mercadopago.rb'
in controller get a this error
TypeError (MercadoPago is not a class)

Rails version 5.1.4
work in Rails version 5.1.2

**Comment by juancolacelli** [comment]
Gemfile:
source :rubygems
gem "mercadopago-sdk", "0.3.4"

$ irb
2.4.0 :001 > require 'mercadopago'
 => true
2.4.0 :002 > MercadoPago
 => MercadoPago
