### ISSUE TITLE
Why cacert.pem passed to Net::HTTP

### ISSUE THREAD

**Issue by chrismo** [mercadopago/sdk-ruby#5]
https://github.com/mercadopago/sdk-ruby/blob/master/lib/mercadopago.rb#L156

Why is the cacert.pem file being passed into Net::HTTP? Articles like the following one recommend against that:

http://www.thoughtcrime.org/blog/strongtrustmanager-mitm/

**Comment by hcasatti** [comment]
This is not needed anymore.
