### ISSUE TITLE
Require failing when `rest-client` is missing

### ISSUE THREAD

**Issue by difernandez** [mercadopago/sdk-ruby#53]
**Describe the bug**
If the gem `rest-client` isn't explicitly installed alongside the sdk, the app will fail when doing `require 'mercadopago'`. I think `rest-client` should be listed as a dependency

**To Reproduce**
Add `mercadopago-sdk` to the Gemfile of an app that doesn't include rest-client and try to require mercadopago

**Expected behavior**
Gem shouldn't require explicit installation of another gem outside of it's declared dependencies

**Comment by micheloliveiramarciano** [comment]
Hola @difernandez , estamos haciendo la corrección, gracias
